version: '2.1'
services:
  tvp-localstack:
    extends:
      file: src/main/docker/localstack.yml
      service: localstack
    networks:
      localbridge:
        aliases:
            - localstack
            - localstack.tvp.com
  tvp-app:
    image: team-vacation-planner:latest
    #build: build/docker
    depends_on:
      - tvp-localstack
    ports:
    - "8365:8365"
    networks:
      localbridge:
        aliases:
          - app
          - app.tvp.com

networks:
  localbridge:
    driver: bridge