version: '2'
services:
    db:
        image: mongo
        restart: always
        environment:
          - MONGO_DATA_DIR=/data/db
        ports:
          - 27017:27017
        networks:
          localbridge:
            aliases:
              - mongo
              - mongo.tvp.com
              - mongo.dev.tvp.com