version: '2.1'

services:
  localstack:
    container_name: tvp-localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8000:8000"
    environment:
      - SERVICES=s3,sts,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"