name: Publish new release to ECR

on:
  push:
    tags:
      - v*
env:
  TAG_ID: version

jobs:
  gettag:
    runs-on: ubuntu-latest
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: docker login -u ${{ secrets.dockerUser }} --password ${{ secrets.dockerSecret }}
      - name: Docker Pull
        run: docker pull teamvacationplanner/team-vacation-planner:latest
      - name: Docker Logout
        run: docker logout
      - name: ECR
        run: |
        docker login -u ${{ secrets.ecrAccessKey }} --password ${{ secrets.ecrSecretKey }}  ${{ secrets.ecrLoginUrl }}
        docker push ${{ secrets.ecrRepo }}/team-vacation-planner:latest
