name: Publish new release to ECR

on:
  push:
    tags:
      - release/
env:
  TAG_ID: version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Integration Test
        run: ./gradlew integrationTest
      - name: Build Image
        if: success()
        with:
          ecrAccessKey: ${{ secrets.ecrAccessKey }}
          ecrSecretKey: ${{ secrets.ecrSecretKey }}
          ecrLoginUrl: ${{ secrets.ecrLoginUrl }}
          ecrRepo: ${{ secrets.ecrRepo }}
        run: |
          ./gradlew dockerCreateDockerfile
          ./gradlew dockerBuildImage
          docker login -u $ecrAccessKey --password $ecrSecretKey $ecrLoginUrl
          docker push $ecrRepo/team-vacation-planner:latest
          docker logout