name: Java CI

on:
  pull_request:
    branches: 
      - master
      - release

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Integration Test
      run: ./gradlew integrationTest
    - name: Build Image
      if: success()
      run: |
        ./gradlew dockerCreateDockerfile
        ./gradlew dockerBuildImage
        docker login -u ${{ secrets.dockerUser }}
        ${{ secrets.dockerSecret }}
        docker push teamvacationplanner/team-vacation-planner
