name: Java CI

on:
  pull_request:
    branches: 
      - master
      - release

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Integration Test
      run: ./gradlew integrationTest
    - name: Build Image
      if: success()
      run: |
        ./gradlew dockerCreateDockerfile
        ./gradlew dockerBuildImage
    - name: Push to Hub
      if: success()
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.dockerUser }}
        PASSWORD: ${{ secrets.dockerSecret }}
        IMAGE_NAME: "teamvacationplanner/team-vacation-planner"
        BUILD_PATH: /github/workspace/build/docker/
        TAG_NAME: "ci"
        LATEST: "true"
